import test from 'ava';
import m from '.';

test('main', t => {
	t.is(m('unicorn', 0), 'unicorns');
	t.is(m('unicorn', 1), 'unicorn');
	t.is(m('unicorn', 2), 'unicorns');
	t.is(m('unicorn', 'horse', 0), 'horse');
	t.is(m('unicorn', 'horse', 1), 'unicorn');
	t.is(m('unicorn', 'horse', 2), 'horse');
	t.is(m('bus', 2), 'buses');
	t.is(m('box', 2), 'boxes');
	t.is(m('fizz', 2), 'fizzes');
	t.is(m('batch', 2), 'batches');
	t.is(m('bush', 2), 'bushes');
	t.is(m('Bush', 2), 'Bushes');
	t.is(m('guppy', 2), 'guppies');
	t.is(m('UNICORN', 2), 'UNICORNS');
	t.is(m('puppY', 2), 'puppIES');
	t.is(m('man', 2), 'men');
	t.is(m('woman', 2), 'women');
	t.is(m('fish', 2), 'fish');
	t.is(m('sheep', 2), 'sheep');
	t.is(m('tooth', 2), 'teeth');
	t.is(m('tomato', 2), 'tomatoes');
	t.is(m('wife', 2), 'wives');
	t.is(m('shelf', 2), 'shelves');
	t.is(m('day', 2), 'days');
	t.is(m('diy', 2), 'diys');
	t.is(m('child', 2), 'children');
	t.is(m('child', 1), 'child');
	t.is(m('unicorn', -1), 'unicorn');
	t.is(m('unicorn', -2), 'unicorns');
	t.is(m('shelf', 1), 'shelf');
	t.is(m('shelf', 2), 'shelves');
	t.is(m('Shelf', 1), 'Shelf');
	t.is(m('Shelf', 2), 'Shelves');
	t.is(m('SHELF', 1), 'SHELF');
	t.is(m('SHELF', 2), 'SHELVES');
});
